### ISSUE TITLE
PersistentHTTP::Error too many connection resets

### ISSUE THREAD

**Issue by cippaciong** [atipugin/telegram-bot-ruby#11]
Hello, I'm facing the following error with versions 0.3.2 and 0.3.4 of your gem (didn't try version 0.3.3), any idea? The error seems to occur randomly to me.
```
/home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:335:in `rescue in block in request': too many connection resets (due to end of file reached - EOFError) after 709 requests on 3292704 (PersistentHTTP::Error)
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:300:in `block in request'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:137:in `with_connection'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:299:in `request'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in `post'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/api.rb:33:in `call'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/api.rb:28:in `method_missing'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:30:in `fetch_updates'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:26:in `block in listen'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:26:in `loop'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:26:in `listen'
        from cippabot.rb:36:in `block in <main>'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:22:in `run'
        from /home/cippaciong/telegrambot/.bundle/ruby/2.2.0/gems/telegram-bot-ruby-0.3.4/lib/telegram/bot/client.rb:10:in `run'
        from cippabot.rb:35:in `<main>'

```

**Comment by atipugin** [comment]
Could you provide your bot's code?

**Comment by cippaciong** [comment]
Sure! The bot is really simple, I wrote it as a sort of exercise since I'm quite new to programming. It's just your example bot with little changes.
```
require 'telegram/bot'
require 'json'
require 'net/http'
require 'uri'
require 'logger'

token = 'my_token'

def random_tumblr(blog)
    url = URI.parse("#{blog}/random")
    res = Net::HTTP.get_response(url)
    @location = res ['location']
end

Telegram::Bot::Client.run(token, logger: Logger.new($stdout)) do |bot|
  bot.listen do |message|
    case message.text
    when /start/i
      bot.api.sendMessage(chat_id: message.chat.id, text: "Hello, #{message.from.first_name}")
    when /help/i
      reply = %Q{/help - Shows this help

      /cabin - Random image from Cabin Porn
      /kitten - Random image from Fluffy Kittens
      /poke - Find Pokemon based on numbers or names
      es: /poke 150 or /poke blastoise

      /capra - Il miglior animale che c'è...
      }
      bot.api.sendMessage(chat_id: message.chat.id, text: reply)
    when /kitten/i
      reply = random_tumblr('http://fluffy-kittens.tumblr.com')
      bot.api.sendMessage(chat_id: message.chat.id, text: reply)
    when /cabin/i
      reply = random_tumblr('http://cabinporn.com')
      bot.api.sendMessage(chat_id: message.chat.id, text: reply)
    when /surprise/i
        bot.api.sendDocument(chat_id: message.chat.id, document: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    when /capra/i
        bot.api.sendVoice(chat_id: message.chat.id, voice: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
    when /poke/i
      split = message.text.split(" ")
      unless split[1].nil?
        uri = URI.parse("http://pokeapi.co/api/v1/pokemon/"+split[1]+"/")
        puts uri
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Get.new(uri.request_uri)
        response = http.request(request)
        body = response.body.to_s
        if body.eql? ""
        else
          my_hash = JSON.parse(body)
          preview = my_hash["pkdx_id"]
          uri = URI.parse("http://pokeapi.co/media/img/" + preview.to_s + ".png")
          reply = uri
          bot.api.sendMessage(chat_id: message.chat.id, text: reply)
        end
      end
    else
        puts "Unknown command"
    end
  end
end
```

**Comment by SergeyAlekseevN** [comment]
it is not the best solution, but I solved the problem this way:
```
begin
    Telegram::Bot::Client.run(token, logger: Logger.new($stdout)) { |bot|
        bot.listen { |message| 
            #some code...    
            puts "User #{message.from.id} says: #{message.text}" 
        }
    }
rescue Telegram::Bot::Exceptions::ResponseError => e
    puts 'bot has been restarted: #{e}'
    retry
rescue PersistentHTTP::Error => e
    puts 'bot has been restarted: #{e}'
    retry
end
```

**Comment by atipugin** [comment]
I did some investigation and found that it might be related to Keep-Alive. I've changed keep-alive setting and pushed changes to "no_keep_alive" branch. Please give it a try. To use that branch change your Gemfile:
```
gem 'telegram-bot-ruby', github: 'atipugin/telegram-bot-ruby', branch: 'no_keep_alive'
```

**Comment by cippaciong** [comment]
Switched to *no_keep_alive* branch, I'll let you know. Thanks!

@SergeyAlekseevN That would actually be an acceptable workaround for my use case!

**Comment by cippaciong** [comment]
@atipugin Hi, I've been testing the *no_keep_alive* branch for a couple of days by now and the error never showed up.

**Comment by atipugin** [comment]
Great! I think 3 days is enough to test and i'll merge these changes into master.

**Comment by atipugin** [comment]
Please update your gem up to 0.3.7

**Comment by cippaciong** [comment]
Great! Thank you :+1:

**Comment by mightymatth** [comment]
This error still persists in version `0.8.3`. Is there any way to avoid it without catching an exception and restarting bot?

Here is the error response I got:
```
/home/matth/.rvm/gems/ruby-2.4.0/gems/telegram-bot-ruby-0.8.3/lib/telegram/bot/api.rb:74:in `call': Telegram API has returned the error. (error_code: "502", uri: "https://api.telegram.org/bot395558391:AAGAyg3EUoPYsl41TmhsKaBcEX7sY5RlRsc/getUpdates") (Telegram::Bot::Exceptions::ResponseError)
```

**Comment by ivanovaleksey** [comment]
@mightymatth maybe I am missing something but is it really a problem with the gem? I received 502 response, isn't it just an errors on Bot API side?

**Comment by atipugin** [comment]
`ResponseError` means server-side error and must be handled manually (based on error code, message etc).

**Comment by mightymatth** [comment]
Alright, I thought it could be handled by gem somehow. However, I think it's worth mentioning users to handle this common error on example in  `README.md`.
