### ISSUE TITLE
Error when answering via ReplyKeyboard button

### ISSUE THREAD

**Issue by Fensterbank** [atipugin/telegram-bot-ruby#125]
I impemented the example using the `ReplyKeyboardMarkup`, but an exception occurs when the user answers with one of the buttons.

    telegram_bot.rb:74:in `block (2 levels) in start': undefined local variable or method `command' for BlaettleBot:Class (NameError)
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:38:in `block in fetch_updates'
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:33:in `each'
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:33:in `fetch_updates'
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:25:in `listen'
        from telegram_bot.rb:53:in `block in start'
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:18:in `run'
        from /home/fred/.rvm/gems/ruby-2.3.3@sblaettle/gems/telegram-bot-ruby-0.7.2/lib/telegram/bot/client.rb:8:in `run'
        from telegram_bot.rb:52:in `start'
        from telegram_bot.rb:99:in `<main>'

I think it has something to do with Bot API 3.0 changes?

**Comment by Fensterbank** [comment]
Sorry, I was blind.
This had nothing to do with this gem.
