### ISSUE TITLE
too many connection resets (due to end of file reached - EOFError) PersistentHTTP::Error

### ISSUE THREAD

**Issue by thibauld** [atipugin/telegram-bot-ruby#18]
Hi,
My bot crashed with this error. From the look of it, it does not seem like it is coming from my code. It happened after my bot was running for 1 or 2 days.
```
/var/lib/gems/2.0.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:335:in `rescue in block in request': too many connection resets (due to end of file reached - EOFError) after 1729 requests on 27144020 (PersistentHTTP::Error)
        from /var/lib/gems/2.0.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:300:in `block in request'
        from /var/lib/gems/2.0.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:137:in `with_connection'
        from /var/lib/gems/2.0.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:299:in `request'
        from /var/lib/gems/2.0.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
        from /var/lib/gems/2.0.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
        from /var/lib/gems/2.0.0/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in `post'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/api.rb:36:in `call'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/api.rb:31:in `method_missing'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/client.rb:34:in `fetch_updates'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/client.rb:29:in `listen'
        from bot.rb:62:in `block in run'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/client.rb:22:in `run'
        from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.6/lib/telegram/bot/client.rb:10:in `run'
        from bot.rb:61:in `run'
        from bot.rb:72:in `<main>'
```

**Comment by atipugin** [comment]
Seems like the old problem (#11) still occurs. The hardest part is that i can't reproduce it (or at least it would a couple of days to check). I've some thoughts but it may take time to test it.

**Comment by thibauld** [comment]
Let me know if I can be of any help. Right now, I am restarting the process every time it crashes so if you want me to put some debug info somewhere so that I can send it to you, I would gladly do so !

**Comment by atipugin** [comment]
Please update gem up to 0.3.9 and let me know ;)

**Comment by thibauld** [comment]
Thanks ! Will do asap !

**Comment by thibauld** [comment]
Hi, after a few days trial, I can say I repeatedly get this error (pretty quickly) : 
```
/var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/api.rb:42:in `call': Telegram API has returned the error. (error_code: "502", uri: "https://api.telegram.org/bot137205796:AAEDirj9Of1oi6_VHoO5BgT1CLLBwDzOapU/getUpdates") (Telegram::Bot::Exceptions::ResponseError)
	from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/api.rb:33:in `method_missing'
	from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/client.rb:34:in `fetch_updates'
	from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/client.rb:29:in `listen'
	from bot.rb:62:in `block in run'
	from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/client.rb:22:in `run'
	from /var/lib/gems/2.0.0/gems/telegram-bot-ruby-0.3.9/lib/telegram/bot/client.rb:10:in `run'
	from bot.rb:61:in `run'
	from bot.rb:72:in `<main>'
```

**Comment by atipugin** [comment]
It looks like Telegram server error and not related to the gem.

**Comment by thibauld** [comment]
Oops... my bad, I forgot to catch the Exception.
Conclusion: it seems good! I will close the issue and reopen it in case the pb resurfaces
