### ISSUE TITLE
Bot crashes when receiving polls

### ISSUE THREAD

**Issue by lukeovalle** [atipugin/telegram-bot-ruby#202]
Bot crashes when Update is a Poll, this is the log

```
Traceback (most recent call last):
        5: from bot.rb:5:in `<main>'
        4: from /usr/lib64/ruby/gems/2.6.0/gems/telegram-bot-ruby-0.10.0/lib/telegram/bot/client.rb:25:in `listen'
        3: from /usr/lib64/ruby/gems/2.6.0/gems/telegram-bot-ruby-0.10.0/lib/telegram/bot/client.rb:33:in `fetch_updates'
        2: from /usr/lib64/ruby/gems/2.6.0/gems/telegram-bot-ruby-0.10.0/lib/telegram/bot/client.rb:33:in `each'
        1: from /usr/lib64/ruby/gems/2.6.0/gems/telegram-bot-ruby-0.10.0/lib/telegram/bot/client.rb:37:in `block in fetch_updates'
/usr/lib64/ruby/gems/2.6.0/gems/telegram-bot-ruby-0.10.0/lib/telegram/bot/client.rb:56:in `log_incoming_message': undefined method `from' for #<Telegram::Bot::Types::Poll:0x000056027c64ca60> (NoMethodError)
```

I believe this is because Poll is the only class in an update that doesn't have a `from` field

**Comment by atipugin** [comment]
Hi @lukeovalle! Indeed `Poll` object doesn't have `#from` attribute. I've fixed it in https://github.com/atipugin/telegram-bot-ruby/commit/267316e5b7e9a02c77d7a0189935348d1c57687d and released `v0.10.1`. Please give it a try.
