### ISSUE TITLE
Faraday Exception on 502

### ISSUE THREAD

**Issue by araishikeiwai** [atipugin/telegram-bot-ruby#48]
Hi,
I've got two bots running, with one using the old version (before Telegram API 2.0) and one using the new one (using Faraday). 

I handle exceptions by
```ruby
rescue StandardError => e
  puts e.message
  puts e.backtrace.select{ |err| err =~ /tulul/ }.join(', ')
  retry
end
```

The old one showed this error message:
```
Telegram API has returned the error. (error_code: "502", uri: "https://api.telegram.org/bot168860534:AAHux5hMU96avnuCcSvJaMF84F8Nnzw9-i0/getUpdates")
/home/araishikeiwai/lycantulul_bot/lib/lycantulul_bot/lycantulul_bot.rb:4:in `block in start', /home/araishikeiwai/lycantulul_bot/lib/lycantulul_bot/lycantulul_bot.rb:3:in `start', /home/araishikeiwai/lycantulul_bot/Rakefile:19:in `block (2 levels) in <top (required)>'
```

When the new one showed:
```
NoMethodError: undefined method `request' for #<Faraday::Response:0x9609a24>
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:26:in `rescue in data'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:23:in `data'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:13:in `to_s'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:83:in `message'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:83:in `rescue in start'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:5:in `start'
/home/araishikeiwai/tulul_stats_bot/Rakefile:17:in `block (2 levels) in <top (required)>'
JSON::ParserError: 757: unexpected token at '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:24:in `data'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:13:in `to_s'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:83:in `message'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:83:in `rescue in start'
/home/araishikeiwai/tulul_stats_bot/lib/tulul_stats_bot/tulul_stats_bot.rb:5:in `start'
/home/araishikeiwai/tulul_stats_bot/Rakefile:17:in `block (2 levels) in <top (required)>'
/home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:26:in `rescue in data': undefined method `request' for #<Faraday::Response:0x9609a24> (NoMethodError)
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:23:in `data'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/telegram-bot-ruby-0.5.0.beta2/lib/telegram/bot/exceptions/response_error.rb:13:in `to_s'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:222:in `message'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:222:in `display_exception_message_details'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:209:in `display_exception_details'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:211:in `display_exception_details'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:211:in `display_exception_details'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:198:in `display_error_message'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:185:in `rescue in standard_exception_handling'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/bin/rake:23:in `load'
        from /home/araishikeiwai/.rvm/gems/ruby-2.1.0/bin/rake:23:in `<main>'
```

**Comment by atipugin** [comment]
Yeah, there was a bug. Please update up to 0.5.0.beta4.

**Comment by araishikeiwai** [comment]
Thanks for the quick response and fix!
