### ISSUE TITLE
SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by filingroove** [atipugin/telegram-bot-ruby#7]
Can't connect to telegram API. This answer can possibly help resolve the issue: http://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read

**SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)**
(Ubuntu 12.04, ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux])

```
/usr/local/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)
	from /usr/local/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /usr/local/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /usr/local/lib/ruby/2.0.0/net/http.rb:857:in `start'
	from /usr/local/lib/ruby/gems/2.0.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:253:in `block in initialize'
	from /usr/local/lib/ruby/gems/2.0.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:194:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:194:in `renew'
	from /usr/local/lib/ruby/gems/2.0.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:102:in `checkout'
	from /usr/local/lib/ruby/gems/2.0.0/gems/gene_pool-1.4.1/lib/gene_pool.rb:134:in `with_connection'
	from /usr/local/lib/ruby/gems/2.0.0/gems/persistent_http-1.0.6/lib/persistent_http.rb:299:in `request'
	from /usr/local/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
	from /usr/local/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
	from /usr/local/lib/ruby/gems/2.0.0/gems/httmultiparty-0.3.16/lib/httmultiparty.rb:124:in `post'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/api.rb:32:in `call'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/api.rb:27:in `method_missing'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:27:in `block in listen'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:26:in `loop'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:26:in `listen'
	from radiokpi-bot.rb:18:in `block in runbot'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:22:in `run'
	from /usr/local/lib/ruby/gems/2.0.0/gems/telegram-bot-ruby-0.3.1/lib/telegram/bot/client.rb:10:in `run'
```

**Comment by atipugin** [comment]
@filingroove, i don't think it's somehow related to this gem. I'm also against hardcoding ssl_version/ciphers settings in the code. Best solution here is to update your openssl and rebuild your ruby.
