### ISSUE TITLE
Conflic another webhook is activate

### ISSUE THREAD

**Issue by JorgeDDW** [atipugin/telegram-bot-ruby#70]
Hi guys me here on my Pokedex :)

This error cant let me use my @poke_bot Telegram bot.

How do i Fix this?
```
/Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/api.rb:66:in `call': Telegram API has returned the error. (ok: "false", error_code: "409", description: "Conflict: another webhook is active") (Telegram::Bot::Exceptions::ResponseError)
	from /Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/api.rb:50:in `method_missing'
	from /Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/client.rb:32:in `fetch_updates'
	from /Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/client.rb:27:in `listen'
	from pokedex.rb:13:in `block in <main>'
	from /Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/client.rb:20:in `run'
	from /Users/Jorge/.rvm/gems/ruby-2.3.0/gems/telegram-bot-ruby-0.5.2/lib/telegram/bot/client.rb:8:in `run'
	from pokedex.rb:12:in `<main>'
```

**Comment by ivanovaleksey** [comment]
Hi.
I faced with the same issue when I accidentally set webhook while using long polling strategy.

You can try to unset the webhook with 
```
response = BOT.api.set_webhook url: ''
p response # you can see what Telegram API response is
```
Or if it would not help maybe you can regenerate `BOT_TOKEN`.

**Comment by JorgeDDW** [comment]
@ivanovaleksey, I create a new token and did not work.

Also using the unset the webhook i get this:

`pokedex.rb:13:in `block in <main>': uninitialized constant BOT (NameError)`

Whats go inside url?
`response = BOT.api.set_webhook url: 'telegram.org/token'`
is that correct?

**Comment by ivanovaleksey** [comment]
`BOT` should be your `Telegram::Bot::Client` instance. You can name it whatever you want.
```
bot = Telegram::Bot::Client.new YOUR_TOKEN
response = bot.api.set_webhook url: ''
p response # you can see what Telegram API response is
```
`url` must be blank. That means that you set webhook to nothing.

**Comment by JorgeDDW** [comment]
This work!
