### ISSUE TITLE
Message nil in log_incoming_message

### ISSUE THREAD

**Issue by TPei** [atipugin/telegram-bot-ruby#87]
when I am trying to start my bot, I get the following error:

```
/var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:60:in `log_incoming_message': undefined method `from' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:41:in `block in fetch_updates'
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:37:in `each'
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:37:in `fetch_updates'
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:29:in `listen'
        from main.rb:10:in `block in <main>'
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:22:in `run'
        from /var/lib/gems/2.3.0/gems/telegram-bot-ruby-0.4.1/lib/telegram/bot/client.rb:10:in `run'
        from main.rb:9:in `<main>'
```

where main.rb:9 ist just
`Telegram::Bot::Client.run(token) do |bot|`

`token` is defined

As far as I can tell it concerns `uid = message.from ? message.from.id : nil` and therefore message would have to be nil.

I think I might have triggered this by editing a message.

**Comment by ivanovaleksey** [comment]
Hi. 
Seems like duplicate of #85 
What gem version are you using?

**Comment by TPei** [comment]
Oh wow, I was running a super old version (0.4.1), I updated and now it works
