### ISSUE TITLE
Weird exception occurs periodically on bot with inline mode enanled

### ISSUE THREAD

**Issue by FiveYellowMice** [atipugin/telegram-bot-ruby#96]
This seems to be only happening on bots with inline mode.

Unfortunately I don't know why this happens, or what kind of information it has received. It just... happens, and it looks like it's something wrong with this library. So here's the backtrace:

```
/var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:59:in `log_incoming_message': undefined method `from' for nil:NilClass (NoMethodError)
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:37:in `block in fetch_updates'
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:33:in `each'
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:33:in `fetch_updates'
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:25:in `listen'
        from /var/lib/labrat/labrat/lib/labrat/telegram.rb:29:in `block (3 levels) in initialize'
        from /var/lib/labrat/labrat/lib/labrat/telegram.rb:26:in `loop'
        from /var/lib/labrat/labrat/lib/labrat/telegram.rb:26:in `block (2 levels) in initialize'
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:18:in `run'
        from /var/lib/labrat/labrat/vendor/bundle/ruby/2.3.0/gems/telegram-bot-ruby-0.7.1/lib/telegram/bot/client.rb:8:in `run'
        from /var/lib/labrat/labrat/lib/labrat/telegram.rb:23:in `block in initialize'
```

I could probably get more information if I know how.

**Comment by ivanovaleksey** [comment]
Hi @FiveYellowMice.
It is probably related to #82 and should be fixed with #95.
